name: Build and Deploy
on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: deflife/paytm:latest
          file: ./docker/Dockerfile.user

      - name: verify image
        run: docker pull deflife/paytm:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull deflife/paytm:latest
            sudo docker stop paytm || true
            sudo docker rm paytm || true
            sudo docker run -e DATABASE_URL=${{secrets.DATABASE_URL}} -e NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}} -e NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}} -d --name paytm -p 3005:3000 deflife/paytm:latest
